name: usuarios-api-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo de pruebas
      - name: Checkout ProjetoMestrefinal2-API
        uses: actions/checkout@v3
        with:
          path: ProjetoMestrefinal2-API

      # Checkout del repo del servidor
      - name: Checkout hub-de-leitura-api
        uses: actions/checkout@v3
        with:
          repository: fabioaraujoqa/hub-de-leitura-api
          path: hub-de-leitura-api

      # Verificar estructura
